[package]
name = "rune-modules"
version = "0.3.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
edition = "2018"
readme = "README.md"
repository = "https://github.com/rune-rs/rune"
homepage = "https://github.com/rune-rs/rune"
documentation = "https://docs.rs/rune-modules"
keywords = ["language", "scripting"]
categories = []
description = """
Native modules for the runestick virtual machine.
"""

[features]
full = ["time", "http", "json", "process"]
time = ["tokio", "tokio/time"]
http = ["reqwest"]
json = ["serde_json"]
process = ["tokio/process"]

[dependencies]
reqwest = {version = "0.10.7", optional = true}
tokio = {version = "0.2.22", optional = true}
serde_json = {version = "1.0.57", optional = true}

runestick = {version = "0.3.0", path = "../runestick"}
