[package]
name = "rune-modules"
version = "0.5.2"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
edition = "2018"
readme = "README.md"
repository = "https://github.com/rune-rs/rune"
homepage = "https://github.com/rune-rs/rune"
documentation = "https://docs.rs/rune-modules"
keywords = ["language", "scripting"]
categories = []
description = """
Native modules for Rune, an embeddable dynamic programming language for Rust. 
"""

[features]
full = ["time", "http", "json", "toml", "process", "fs"]
time = ["tokio", "tokio/time"]
fs = ["tokio", "tokio/fs"]
http = ["reqwest"]
json = ["serde_json"]
process = ["tokio/process"]

[dependencies]
reqwest = {version = "0.10.7", optional = true}
tokio = {version = "0.2.22", optional = true}
serde_json = {version = "1.0.57", optional = true}
toml = {version = "0.5.6", optional = true}

runestick = {version = "0.5.2", path = "../runestick"}

[package.metadata.docs.rs]
all-features = true
