[package]
name = "rune-cli"
version = "0.0.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "0.2.22", features = ["rt-core", "net", "fs", "macros"]}
reqwest = "0.10.7"
env_logger = "0.7.1"

rune = {version = "0.0.0", path = "../rune"}
st = {version = "0.0.0", path = "../st"}
st-http = {version = "0.0.0", path = "../st-http"}
st-json = {version = "0.0.0", path = "../st-json"}
codespan-reporting = "0.9.5"

anyhow = "1.0.32"

[[bin]]
name = "rune"
path = "src/main.rs"