[package]
name = "rune-cli"
version = "0.2.1"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
edition = "2018"
readme = "README.md"
repository = "https://github.com/udoprog/stk"
homepage = "https://github.com/udoprog/stk"
documentation = "https://docs.rs/rune-cli"
keywords = ["language", "scripting"]
categories = []
description = """
A standalone interpreter for Rune.
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "0.2.22", features = ["rt-core", "net", "fs", "macros"]}
reqwest = "0.10.7"
env_logger = "0.7.1"

rune = {version = "0.2.1", path = "../rune"}
stk = {version = "0.2.1", path = "../stk"}
stk-http = {version = "0.2.1", path = "../stk-http"}
stk-json = {version = "0.2.1", path = "../stk-json"}
stk-time = {version = "0.2.1", path = "../stk-time"}
codespan-reporting = "0.9.5"

anyhow = "1.0.32"

[[bin]]
name = "rune"
path = "src/main.rs"