[package]
name = "rune-cli"
version = "0.5.3"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
edition = "2018"
readme = "README.md"
repository = "https://github.com/rune-rs/rune"
homepage = "https://github.com/rune-rs/rune"
documentation = "https://docs.rs/rune-cli"
keywords = ["language", "scripting"]
categories = []
description = """
An interpreter for Rune, an embeddable dynamic programming language for Rust. 
"""

[dependencies]
tokio = {version = "0.2.22", features = ["rt-core", "net", "fs", "macros"]}
env_logger = "0.7.1"
codespan-reporting = "0.9.5"
anyhow = "1.0.32"

rune = {version = "0.5.3", path = "../rune", features = ["modules"]}
runestick = {version = "0.5.3", path = "../runestick"}

[[bin]]
name = "rune"
path = "src/main.rs"