[workspace]
members = [
    "crates/runestick",
    "crates/runestick-http",
    "crates/runestick-json",
    "crates/runestick-time",
    "crates/rune",
    "crates/rune-cli",
]

default-members = [
    "crates/runestick",
    "crates/rune",
    "crates/rune-cli",
]