[workspace]
members = [
    "crates/st",
    "crates/st-http",
    "crates/st-json",
    "crates/rune",
    "crates/rune-cli",
]

default-members = [
    "crates/st",
    "crates/rune",
    "crates/rune-cli",
]