[workspace]
members = [
    "crates/stk",
    "crates/stk-http",
    "crates/stk-json",
    "crates/rune",
    "crates/rune-cli",
]

default-members = [
    "crates/stk",
    "crates/rune",
    "crates/rune-cli",
]