[package]
name = "runestick"
version = "0.2.2"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
edition = "2018"
readme = "README.md"
repository = "https://github.com/udoprog/runestick"
homepage = "https://github.com/udoprog/runestick"
documentation = "https://docs.rs/runestick"
keywords = ["language", "scripting"]
categories = []
description = """
The simple stack-based virtual machine.
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.7.1"
log = "0.4.11"
twox-hash = "1.5.0"
thiserror = "1.0.20"
slab = "0.4.2"
hashbrown = "0.8.1"
serde = "1.0.114"
itoa = "0.4.6"
ryu = "1.0"
# used to store errors raised in user-defined functions.
anyhow = "1.0.32"
futures = "0.3.5"

[dev-dependencies]
tokio = {version = "0.2.22", features = ["full"]}