[package]
name = "st-json"
version = "0.0.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
description = """
An JSON module based on serde_json for st.
"""

[dependencies]
anyhow = "1.0.32"
serde_json = "1.0.57"
st = {version = "0.0.0", path = "../st"}