[package]
name = "rune"
version = "0.2.2"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
edition = "2018"
readme = "README.md"
repository = "https://github.com/udoprog/runestick"
homepage = "https://github.com/udoprog/runestick"
documentation = "https://docs.rs/rune"
keywords = ["language", "scripting"]
categories = []
description = """
Rune is a simple dynamic language for the runestick virtual machine.
"""

[features]
default = ["runtime"]
runtime = ["codespan-reporting"]

[dependencies]
runestick = {version = "0.2.2", path = "../runestick"}
thiserror = "1.0.20"
log = "0.4.11"
codespan-reporting = {version = "0.9.5", optional = true}
slab = "0.4.2"
hashbrown = "0.8.2"

[dev-dependencies]
futures-executor = "0.3.5"