[package]
name = "rune"
version = "0.2.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
edition = "2018"
readme = "README.md"
repository = "https://github.com/udoprog/stk"
homepage = "https://github.com/udoprog/stk"
documentation = "https://docs.rs/rune"
keywords = ["language", "scripting"]
categories = []
description = """
Rune is a simple dynamic language for the stk virtual machine.
"""

[features]
default = ["runtime"]
runtime = ["anyhow", "codespan-reporting"]

[dependencies]
stk = {version = "0.2.0", path = "../stk"}
thiserror = "1.0.20"
log = "0.4.11"
codespan-reporting = {version = "0.9.5", optional = true}
slab = "0.4.2"
anyhow = {version = "1.0.32", optional = true}

[dev-dependencies]
tokio = {version = "0.2", features = ["full"]}
anyhow = "1"